Clear-Host
iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
cinst act-cli -y
cinst autohotkey -y
cinst autohotkey.install -y
cinst autohotkey.portable -y
cinst azure-data-studio -y
cinst backblaze -y
cinst bat -y
cinst bicep -y
cinst Boxstarter -y
cinst Boxstarter.Bootstrapper -y
cinst Boxstarter.Chocolatey -y
cinst Boxstarter.Common -y
cinst Boxstarter.HyperV -y
cinst Boxstarter.WinConfig -y
cinst cascadia-code-nerd-font -y
cinst checksum -y
cinst choco-cleaner -y
cinst choco-nuspec-checker -y
cinst choco-protocol-support -y
cinst chocolatey -y
cinst chocolatey-azuredatastudio.extension -y
cinst chocolatey-core.extension -y
cinst chocolatey-dotnetfx.extension -y
cinst chocolatey-font-helpers.extension -y
cinst chocolatey-misc-helpers.extension -y
cinst chocolatey-visualstudio.extension -y
cinst chocolatey-windowsupdate.extension -y
cinst DotNet4.5.2 -y
cinst DotNet4.6.1 -y
cinst dotnet4.7 -y
cinst dotnetfx -y
cinst Everything -y
cinst expandrive -y
cinst freefilesync -y
cinst fzf -y
cinst gh -y
cinst googler -y
cinst gping -y
cinst httpie -y
cinst InnoSetup -y
cinst instchoco -y
cinst intel-dsa -y
cinst jp -y
cinst jq -y
cinst KB2919355 -y
cinst KB2919442 -y
cinst KB2999226 -y
cinst KB3033929 -y
cinst KB3035131 -y
cinst less -y
cinst Ln -y
cinst lsd -y
cinst pngoptimizer.commandline -y
cinst PowerShell -y
cinst python -y
cinst python3 -y
cinst qpdf -y
cinst qttabbar -y
cinst rapidee -y
cinst ripgrep -y
cinst sql-server-management-studio -y
cinst sqlitebrowser.install -y
cinst sqlpackage -y
cinst Sudo -y
cinst terracreds -y
cinst terraform -y
cinst terragrunt -y
cinst tflint -y
cinst tldr -y
cinst tldr-plusplus -y
cinst toggl -y
cinst uniextract.install -y
cinst ussf -y
cinst vcredist140 -y
cinst vcredist2010 -y
cinst vcredist2013 -y
cinst vcredist2015 -y
cinst vcredist2017 -y
cinst visualstudio-installer -y
cinst visualstudio2019-workload-vctools -y
cinst visualstudio2019buildtools -y
cinst vscode-insiders -y
cinst vscode-insiders.install -y
cinst yori -y
cinst youtube-dl -y
cinst yq -y
Clear-Host
echo "All done!"
Pause
